version: '3.8'

services:
  solva-project-backend-service:
    image: 'abylai/project-solva-repo'
    container_name: solva-backend-container
    depends_on:
      - my-project-database-service
    environment:
      - SPRING_APPLICATION_NAME=transaction_api_microservice
      - SPRING_DATASOURCE_URL=jdbc:postgresql://my-project-database-service:5432/transactions
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - feign.client.alphaVantageClient.url=https://www.alphavantage.co
      - CURRENCY_UPDATE_SCHEDULE=0 0 10 * * *
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
      - SPRING_FLYWAY_SCHEMAS=public
    ports:
      - "8888:7777"

  my-project-database-service:
    image: 'postgres'
    container_name: transaction-bd
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transactions
    ports:
      - "2345:5432"
